### ISSUE TITLE
It would be nice to have the ability to set request headers

### ISSUE THREAD

**Issue by VanTanev** [tcstool/NoSQLMap#24]
When dealing with things like JWT, we need to be able to set the `Authorization` header. There are probably other uses as well.

**Comment by tcstool** [comment]
Duly noted.  I'm working on some other projects right now, but I'll add this in the next release.

**Comment by deadstar1** [comment]
@tcstool HI! it is possible to  pentest a JSON Based web app with this tool. this video only demonstrate a nosql Injection on url parameter https://www.youtube.com/watch?v=XshPcuX9N2I , how about a JSON based app??

**Comment by tcstool** [comment]
I would say it depends on what you mean by a "JSON based app".  If you are referring to JSON being submitted from the client side back to the server, then no it cannot do that but it's something I'd like to get to someday.  However if you are referring to the server building JSON from more "traditional" submitted input (such as the example here:  http://blog.websecurify.com/2014/08/hacking-nodejs-and-mongodb.html) then it will perform these kinds of tests.

**Comment by deadstar1** [comment]
hmmm. i am referring to the first one, i hope it will be added on the future. thank you :)

**Comment by darinrogers** [comment]
I'm curious why this is closed. Is the feature to send headers in there? If so, I can't find it. In my case, I'd just like to send a session ID cookie. I think that's a pretty common case. As of now, I can only test non-authenticated stuff, which isn't much and certainly isn't the bulk of important stuff for my application.

**Comment by codingo** [comment]
As you mentioned, this was referenced in #36 as it was merged in #37
