### ISSUE TITLE
Options bugs

### ISSUE THREAD

**Issue by reider-roque** [tcstool/NoSQLMap#27]
1. Option 4 (Toggle HTTPS) and 9 (Toggle Verbose Mode) aren't saved to the configuration file.

2. Option 6. Despite showing the default being GET one still has to explicitly select the GET option. Otherwise `requestHeaders` variable is not set and the app erroneously reports that *Looks like the server didn't respond.  Check your options.*, while the truth is that line 834 --

    `req = urllib2.Request(appURL, None, requestHeaders)`

-- just throws an exception because of the undefined `requestHeaders variable`. So the `requestHeaders` should by default be initialized with an empty dict and make their way into the configuration file.

**Comment by tcstool** [comment]
Thanks! I'll take a look at these tonight.

**Comment by tcstool** [comment]
These issues should be fixed.  Try it out and let me know.  Feel free to commit any fixes as well.

**Comment by reider-roque** [comment]
Thank you for quick response and fix. I'll try it later and let you know if something is not working :)
