### ISSUE TITLE
Fails to validate ip/subnet on a valid mongo connection

### ISSUE THREAD

**Issue by RasPhilCo** [tcstool/NoSQLMap#28]
Default Access Scanner fails with "Couldn't connect to <ip>" on a valid mongo connection.

From pymongo docs: "The MongoClient.disconnect() method is removed; it was a synonym for close()."

**Comment by snowshoe-squad** [comment]
This had been fixed by merge commit 898a60b. I reference the wrong issue number in my pull request to auto-close this issue.

**Comment by RasPhilCo** [comment]
This had been fixed by merge commit 898a60b. I reference the wrong issue number in my pull request to auto-close this issue.

**Comment by tcstool** [comment]
Thanks!
