### ISSUE TITLE
Counter-intuitive way to send headers

### ISSUE THREAD

**Issue by darinrogers** [tcstool/NoSQLMap#36]
It looks like the way to send a header for e.g. a session ID, is by setting option 6 to specify GET or POST. This is counter-intuitive if you're just sending a bunch of GETs and leaving the default. I'd recommend either something in the docs or making headers a separate option.

**Comment by tcstool** [comment]
I agree.  I didn't write that part, it was generously contributed  It's on
my list of things to clean up, but right now I'm low on free time to get
another release out the door.  If you'd like to contribute it would be
greatly appreciated.

**Comment by codingo** [comment]
@darinrogers @tcstool Closing this issue as this appears to have been merged into master already. Please reply if you believe I have closed this in error.
