### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by nv1t** [tcstool/NoSQLMap#39]
It would be nice to support testing through a HTTP Proxy. So one can use Burp to proxy. Think of Corporate Networks with NTLM Auth Proxys.

**Comment by tcstool** [comment]
If I'm not mistaken, urllib should use the global enviornment variable http_proxy to determine which http proxy server to use.  So you would do something from your shell like:

$export http_proxy='http://myproxy.com:1234'

This should cause the HTTP traffic generated by NoSQLMap to route through the proxy.  If this doesn't work let me know and I'll add it into the options. I'm rewriting all the HTTP handling in the tool, I just have been really busy for the past few months.
