### ISSUE TITLE
changing options after failed attacks

### ISSUE THREAD

**Issue by silverpenguin** [tcstool/NoSQLMap#42]
Trying to run an attack through options 2 and 3 then receiving:

>  Checking to see if credentials are needed...
> Couldn't connect to Mongo server.

When this is recieved and you try to adjust the settings within option 1 the following error occurs:

> Traceback (most recent call last):
>   File "./nosqlmap.py", line 1752, in <module>
>     main()
>   File "./nosqlmap.py", line 60, in main
>     mainMenu()
>   File "./nosqlmap.py", line 93, in mainMenu
>     options()
>   File "./nosqlmap.py", line 199, in options
>     while optSelect:
> UnboundLocalError: local variable 'optSelect' referenced before assignment

**Comment by silverpenguin** [comment]
reading through previous bugs found this issue posted within another and the issue was fixed though the fix does not seem pushed to the main branch ?

**Comment by tcstool** [comment]
Did you clone from 0.5? The fix should have been pushed there.

**Comment by silverpenguin** [comment]
yes it was because of that, the default download was 0.5 my own mistake for just downloading I guess, I just quickly hacked them in for speed but will be downloading the updated 0.6 (will soon be contributing to development)

**Comment by tcstool** [comment]
So I wouldn't use 0.6 yet.  It's a super buggy work in progress :-).  I'd
love some help working on it though.  If you want to shoot me some contact
info over to nosqlmap@gmail.com, I can give you some things I need a hand
with.  The project has outgrown my free time, but I'm doing my best.

**Comment by silverpenguin** [comment]
I dropped you an email!
